piro17-Archive/FilmArchive

signature_parser.py
=> [test]머지테스트

limitedframes/views.py, static/css/limited.css, static/css/limitedlife.css, static/css/moredetail.css, templates/limitedframes/limited.html, templates/limitedframes/limitedlife.html, templates/limitedframes/limitedphotoism.html, templates/limitedframes/limitedsignature.html, templates/users/main.html
=> [design] 한정판 페이지 완료

framesharings/views.py
=> [test]풀리퀘스트 이슈 연동

limitedframes/views.py
=> [test]test2

users/urls.py
=> [design] 메인페이지 변경

static/css/album.css
=> [design] 글 추가 버튼 정렬 맞추기

static/js/albumswiper.js
=> [design] swiper autoplay 적용

static/css/login.css, templates/users/login.html
=> [design] 비밀번호 찾기 버튼, 로그인 hr 조절

static/css/main.css
=> [design] 반응형 구현

static/css/album.css, static/css/login.css, templates/albums/albumdetail.html
=> [design] 삭제 버튼 icon으로 바꾸기

static/css/mypage.css, templates/users/delete_user.html, templates/users/signup.html
=> [design] 회원탈퇴 전체 페이지

templates/framesharings/frame.html
=> [fix]추천,찜 디자인고침

templates/framesharings/frame.html
=> [fix] 추천css 수정

static/css/main.css, templates/users/main.html
=> [design] 주간 Best 디자인

static/css/album.css, templates/albums/albumcalendar.html
=> [design] 캘린더 페이지

templates/albums/albumcalendar.html
=> [fix]캘린더 색상 수정

static/css/album.css, templates/albums/album.html, templates/albums/albumdetail.html
=> [design] 디테일 페이지 캘린더 버튼

limitedframes/urls.py, limitedframes/views.py, static/css/limitedlife.css, templates/limitedframes/limited.html, templates/limitedframes/limitedlifedetail.html
=> [design] 한정판 프레임 디테일로 가는 link 없애기

static/css/common.css, static/css/main.css, templates/users/main.html
=> [design] 폰트 적용과 footer 수정

templates/limitedframes/limitedlife.html
=> [fix]한정판 오류수정

templates/users/login.html, users/views.py
=> [fix] 로그인 실패시 form 사라짐 해결

static/css/mypage.css
=> [fix] class이름 겹침 해결

static/css/main.css, static/js/navbar.js, templates/users/main.html
=> [feature] navbar scroll 반응형 구현

templates/maps/map.html
=> [feat] 카카오지도 내주변 검색  목록추가

framesharings/views.py, templates/framesharings/framecreate.html
=> [feat]태그선택 수정

static/css/common.css, static/css/login.css, static/css/main.css, static/css/signup.css, static/js/navbar.js, templates/users/main.html
=> [fix] login, navbar

static/css/album.css
=> [design] 캘린더 아이콘 위치 수정

static/css/login.css, templates/registration/password_reset_complete.html, templates/registration/password_reset_confirm.html, templates/registration/password_reset_done.html, templates/users/find_username.html, templates/users/find_username_complete.html
=> [design] 아이디 찾기, 비밀번호 찾기

config/settings.py, static/css/album.css, static/css/common.css, static/css/frame.css, static/css/main.css, static/js/navbar.js
=> [design] width 34rem으로 맞추기

static/css/common.css, static/js/navbar.js
=> [fix] navbar 오류 수정

templates/users/main.html
=> [fix] 메인에 지도링크추가

static/css/main.css, templates/users/main.html
=> [fix] 포토부스 위치, 제작 프레임 공유 바꾸기

albums/views.py, templates/albums/albumcreate.html, templates/framesharings/framecreate.html
=> [fix] 앨범,프레임공유 사진필수경고

static/css/map.css, templates/maps/map.html, templates/users/main.html
=> [design] 포토부스 위치 페이지

config/settings.py
=> [fix] settings 수정

.gitignore, config/settings.py, photoism_parser.py, signature_parser.py
=> [feat] 배포 리눅스 변경사항

templates/users/main.html
=> [fix] main swiper 자세히 보기 링크 수정

static/css/album.css, static/css/frame.css, templates/albums/albumcreate.html, templates/framesharings/framecreate.html
=> [design] 사진 필수

static/css/common.css, static/css/main.css, templates/users/main.html
=> [design] footer

static/css/login.css, templates/users/find_username_complete.html
=> [design] 아이디 찾기

templates/maps/map.html
=> [feat]지도 목록 마우스오버 안움직이게 변경

static/css/frame.css, static/css/mypage.css, templates/users/mypage.html, templates/users/saved_detail.html
=> [design] 마이페이지 저장목록

static/css/album.css, templates/albums/albumupdate.html
=> [fix] 글 수정 페이지 동영상 url 수정

static/css/common.css, static/css/map.css, static/js/map.js, templates/maps/map.html, templates/users/main.html
=> [design] 포토부스 위치

static/css/main.css
=> [fix] 메인 사진 비율 맞추기

static/css/map.css, templates/maps/map.html
=> [feat]지도 버튼 수정

templates/framesharings/framedetail.html
=> [fix] 프레임디테일페이지 하트수정

static/css/login.css, templates/users/login.html, users/views.py
=> [design] 로그인 실패 문구

static/css/map.css, templates/maps/map.html
=> [design] 포토부스 검색, 버튼

templates/framesharings/framedetail.html
=> [fix]프레임 디테일 추천수ajax

config/settings.py, static/css/album.css, static/js/albumswiper.js, templates/albums/albumdetail.html, templates/users/main.html
=> [design] 앨범 디테일 swiper

static/css/frame.css, templates/framesharings/frameupdate.html
=> [fix] class겹침 수정

templates/albums/albumcalendar.html, templates/framesharings/frame.html
=> [fix] 프레임 비로그인 수정

albums/views.py, framesharings/views.py, templates/albums/album.html, templates/albums/albumcalendar.html, templates/framesharings/frame.html, templates/framesharings/framedetail.html, templates/maps/map.html
=> [fix] 정렬중인거표시,캘린더 수정, 지도 폰화면 자동이동,삭제수정버튼 생성유저만

config/settings.py, static/css/album.css, static/css/frame.css, templates/albums/albumcreate.html, templates/albums/albumupdate.html, templates/framesharings/framecreate.html, templates/framesharings/frameupdate.html
=> [design] 앨범 padding 조절

templates/registration/password_reset_confirm.html
=> [design] 비밀번호 재설정

static/css/signup.css
=> [fix] 회원가입 양식 깨짐 css 수정

static/css/signup.css
=> [design] 회원가입 에러 메세지
